### ISSUE TITLE
What is the criterion for dividing the "elements" of the css into components and objects?

### ISSUE THREAD

**Issue by victorsilent** [lunaroja/ama#1]
What is the criterion for dividing the "elements" of the css into components and objects? What's the difference?

https://github.com/dropbox/scooter

**Comment by lunaroja** [comment]
👋  From the https://github.com/dropbox/css-style-guide
>.o- for CSS objects. Objects are usually common design patterns (like the Flag object). Modifying these classes could have severe knock-on effects.
> .c- for CSS components. Components are designed pieces of UI—think buttons, inputs, modals, and banners.

Scooter has been deprecated internal use. Let me know if you have any other questions of recommendations.
